### ISSUE TITLE
Text misalignment

### ISSUE THREAD

**Issue by josephtf2** [Hypnootize/OMP-Hud#1]
Hey,

the text is not aligned with the health crosses when either speccing someone or when you are overhealed/weak

**Comment by Hypnootize** [comment]
Its fine for me as you can see here https://i.imgur.com/dnrWRqz.jpg so I'm not sure. Try to install the hud fonts first of all like that https://i.imgur.com/U39x9Db.png

if it doesn't work try to also do that:
- Go in C:\Windows\Fonts 
- Find and delete every font you find with "Futura" in it
- Reinstall the hud fonts (install FuturaStd-Heavy/FuturaStd-Medium. Don't install the mac versions they might cause problems maybe i haven't tested)
