### ISSUE TITLE
Fonts problems

### ISSUE THREAD

**Issue by Detenog** [Hypnootize/OMP-Hud#3]
There's a problem with the font for this HUD. I noticed the fonts go a little bit down, making the HUD cut off in some parts. Here's some screenshots. (I'll be checking to see if it is maybe my TF2 the problem).

https://steamcommunity.com/sharedfiles/filedetails/?id=1801615409
(1st Edit) https://steamcommunity.com/id/73197318/screenshot/777351578729205196
(2nd Edit) As it seems, the problem it's the HUD or the font provided. Because most part of the HUD get cut, in the Main Menu the problem can be seen mroe properly.

**Comment by Hypnootize** [comment]
Try the fixes i wrote down here and let me know if they fix this problem 
https://github.com/Hypnootize/OMP-Hud/issues/1

**Comment by Detenog** [comment]
Seems like the fonts I had installed were wrong. Thanks!
